name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Create config file
        run: |
          mkdir -p staging
          cat <<END > staging/systeme-io-config.php
          <?php
          define('API_BASE_URL', 'https://api.systeme.io');
          define('API_KEY', '${{ secrets.SYSTEME_IO_API_KEY }}');
          END

      - name: Upload files via lftp
        run: |
          lftp <<END
          set ssl:verify-certificate false
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ftp.${{ secrets.DOMAIN }}
          cd /domains/${{ secrets.DOMAIN }}
          put htdocs/add-systeme-io-contact.php -o public_html/add-systeme-io-contact-test.php
          put staging/systeme-io-config.php -o public_html/.private/add-systeme-io-contact-test.php
          bye
          END

      - name: Clean up
        if: always()
        run: |
          make kill || true
          rm -rf staging
